routes:
# =========================
# Health Check Microservice
# =========================

- regex: '^/health(/*[a-zA-Z0-9]*)?'
  inputModel: main.daos.Healthcheck
  outputModel: main.daos.Healthcheck
  controller: main.controllers.HealthcheckController
  shouldValidatePost: true
  shouldValidatePut: true
  shouldValidateGet: false

- regex: '^/dbhealth(/*[a-zA-Z0-9]*)?'
  inputModel: main.daos.Healthcheck
  outputModel: main.daos.Healthcheck
  controller: main.controllers.DatabaseHealthcheckController
  shouldValidatePost: true
  shouldValidatePut: true
  shouldValidateGet: false

# =========================
# User Account Microservice
# =========================

- regex: '^/user(/*[a-zA-Z0-9]*)?'
  inputModel: main.daos.UserAccount
  outputModel: main.daos.UserAccount
  controller: main.controllers.UserAccountController
  shouldValidatePost: false
  shouldValidatePut: true
  shouldValidateGet: true

  # =========================
  # User Microservice
  # =========================

  - regex: '^/user_test(/*[a-zA-Z0-9]*)?'
    inputModel: main.daos.UserNamespace
    outputModel: main.daos.User
    controller: main.controllers.UserController
    shouldValidatePost: true
    shouldValidatePut: true
    shouldValidateGet: true

